/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gui;

import Agents.AgentCommon.Agent;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author gregor
 */
public class GameStatus extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form asdf
     */
    private Agent agent;
    public GameStatus(Agent agent) {
        initComponents();
        this.agent = agent;
        this.agent.addObserver(this);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticksLabel = new javax.swing.JTextField();
        healthLabel = new javax.swing.JTextField();
        twineCount = new javax.swing.JTextField();
        twineCount1 = new javax.swing.JTextField();
        twineCount2 = new javax.swing.JTextField();
        twineCount3 = new javax.swing.JTextField();
        twineCount4 = new javax.swing.JTextField();
        twineCount5 = new javax.swing.JTextField();

        setFocusable(false);

        ticksLabel.setText("TimeTicks:");
        ticksLabel.setAutoscrolls(false);
        ticksLabel.setFocusable(false);

        healthLabel.setText("Health:");
        healthLabel.setAutoscrolls(false);
        healthLabel.setFocusable(false);

        twineCount.setText("Whining Twine Count:");
        twineCount.setAutoscrolls(false);
        twineCount.setFocusable(false);
        twineCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twineCountActionPerformed(evt);
            }
        });

        twineCount1.setText("Excuse Count:");
        twineCount1.setAutoscrolls(false);
        twineCount1.setFocusable(false);
        twineCount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twineCount1ActionPerformed(evt);
            }
        });

        twineCount2.setText("Bomb Count:");
        twineCount2.setAutoscrolls(false);
        twineCount2.setFocusable(false);
        twineCount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twineCount2ActionPerformed(evt);
            }
        });

        twineCount3.setText("Kill Count:");
        twineCount3.setAutoscrolls(false);
        twineCount3.setFocusable(false);
        twineCount3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twineCount3ActionPerformed(evt);
            }
        });

        twineCount4.setText("Twine Generator Count:");
        twineCount4.setAutoscrolls(false);
        twineCount4.setFocusable(false);
        twineCount4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twineCount4ActionPerformed(evt);
            }
        });

        twineCount5.setText("Excuese Generator Count:");
        twineCount5.setAutoscrolls(false);
        twineCount5.setFocusable(false);
        twineCount5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twineCount5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(twineCount5, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(twineCount4)
                    .addComponent(twineCount3)
                    .addComponent(twineCount2)
                    .addComponent(twineCount1)
                    .addComponent(twineCount)
                    .addComponent(ticksLabel)
                    .addComponent(healthLabel))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(healthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ticksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twineCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twineCount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twineCount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twineCount3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twineCount4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twineCount5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void twineCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twineCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twineCountActionPerformed

    private void twineCount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twineCount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twineCount1ActionPerformed

    private void twineCount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twineCount2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twineCount2ActionPerformed

    private void twineCount3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twineCount3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twineCount3ActionPerformed

    private void twineCount4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twineCount4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twineCount4ActionPerformed

    private void twineCount5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twineCount5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twineCount5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField healthLabel;
    private javax.swing.JTextField ticksLabel;
    private javax.swing.JTextField twineCount;
    private javax.swing.JTextField twineCount1;
    private javax.swing.JTextField twineCount2;
    private javax.swing.JTextField twineCount3;
    private javax.swing.JTextField twineCount4;
    private javax.swing.JTextField twineCount5;
    // End of variables declaration//GEN-END:variables
    private org.jdesktop.beansbinding.BindingGroup myBindings;

    @Override
    public void update(Observable o, Object arg) {
        healthLabel.setText("Health : " + this.agent.gethealth());
        repaint();
        validate();
    }
}
